# Generated by Django 3.1.7 on 2021-03-11 17:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('category', models.IntegerField(choices=[(0, 'Inne'), (1, 'Kino'), (2, 'Teatr'), (3, 'Koncert')], default=0)),
                ('date_from', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_to', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(40)])),
                ('event_image', models.ImageField(blank=True, height_field=600, max_length=1000, null=True, upload_to='event_image', width_field=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='event_manager_app.event')),
            ],
        ),
    ]
